
title = "Tales Gomes"
author = "Tales Gomes"
#copyright = "2022"
description = "Engenheiro da Computação | Analista de dados | Ciêntista de dados"
profilePicture = "images/profile.png"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"
# relatedPosts = true
# numberOfRelatedPosts = 3


reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

[params]
contentratio = 0.7
#hidesidebar = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

[plausibleAnalytics]
# domain = "example.com"
# serverURL = "https://analytics.example.com"

[umami]
# serverURL = "example.com"
# id = "94db1cb1-74f4-4a40-ad6c-962362670409"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/talesgomes27/"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/talesgomes27/"

[[socialIcons]]
icon = "fab fa-twitter-square"
title = "twitter"
url = "https://twitter.com/talesgomes27"


[[socialIcons]]
icon = "fas fa-sitemap"
title = "Datacam profile"
url = "https://www.datacamp.com/profile/talesgomes27"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:talesgomes27@gmail.com"


[[socialIcons]]
icon = "fas fa-file-alt"
title = "resume"
url = "https://rawcdn.githack.com/talesgomes27/curriculo/1428dec4b914920bfae2ab06d8dc09492e8a5948/curriculo/curriculo.pdf"


